version: "3"
services:
    postgres:
        image: postgres:13
        ports:
            - 5432:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=qwerty1234567

volumes:
    postgres_data: {}
